src/Entity/Intervention.php
<?php

namespace App\Entity;

use App\Repository\InterventionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Avion;

#[ORM\Entity(repositoryClass: InterventionRepository::class)]
class Intervention
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Avion::class)]
    #[ORM\JoinColumn(name: 'avion_immatriculation', referencedColumnName: 'immatriculation', nullable: false)]
    private Avion $avion;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?TypeIntervention $InterventionType = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $InterventionCommentaire = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $InterventionDateCreation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $InterventionDateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $InterventionDateFin = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAvion(): Avion
    {
        return $this->avion;
    }

    public function setInterventionAvion(Avion $avion): self
    {
        $this->avion = $avion;

        return $this;
    }

    public function getInterventionType(): ?TypeIntervention
    {
        return $this->InterventionType;
    }

    public function setInterventionType(?TypeIntervention $InterventionType): static
    {
        $this->InterventionType = $InterventionType;

        return $this;
    }

    public function getInterventionCommentaire(): ?string
    {
        return $this->InterventionCommentaire;
    }

    public function setInterventionCommentaire(?string $InterventionCommentaire): static
    {
        $this->InterventionCommentaire = $InterventionCommentaire;

        return $this;
    }

    public function getInterventionDateCreation(): ?\DateTimeInterface
    {
        return $this->InterventionDateCreation;
    }

    public function setInterventionDateCreation(\DateTimeInterface $InterventionDateCreation): static
    {
        $this->InterventionDateCreation = $InterventionDateCreation;

        return $this;
    }

    public function getInterventionDateDebut(): ?\DateTimeInterface
    {
        return $this->InterventionDateDebut;
    }

    public function setInterventionDateDebut(\DateTimeInterface $InterventionDateDebut): static
    {
        $this->InterventionDateDebut = $InterventionDateDebut;

        return $this;
    }

    public function getInterventionDateFin(): ?\DateTimeInterface
    {
        return $this->InterventionDateFin;
    }

    public function setInterventionDateFin(\DateTimeInterface $InterventionDateFin): static
    {
        $this->InterventionDateFin = $InterventionDateFin;

        return $this;
    }
}

src/Controller/InterventionController.php
<?php

namespace App\Controller;
use App\Repository\AvionRepository;
use App\Repository\InterventionRepository;

use Doctrine\ORM\EntityManagerInterface;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;


class InterventionController extends AbstractController
{
    #[Route('/', name: 'app_intervention')]
    public function index(): Response
    {
        return $this->render('intervention/index.html.twig', [
            
        ]);
    }

    // Page pour toute les interventions
    #[Route('/liste-intervention', name: 'liste_intervention')]
    public function liste(
        InterventionRepository $interventionRepository, 
        AvionRepository $avionRepository
        ): Response
    {
        $interventions = $interventionRepository->findAll();
        $avions = $avionRepository->findAll();
        
        return $this->render('intervention/liste.html.twig', [
            'interventions'=> $interventions,
            'avions'=> $avions,
        ]);
    }

    // Page pour chaque intervention
    #[Route('/intervention/{id}', name:'intervention', methods:['GET', 'POST'])]
    public function interventionDetail(
        int $id, 
        InterventionRepository $interventionRepository, 
        AvionRepository $avionRepository,
        Request $request, 
        EntityManagerInterface $em
        ): Response
    {
        $intervention = $interventionRepository->find($id);
        //vérifier si intervention existe
        if (!$intervention) {
            throw $this->createNotFoundException("Cette intervention n'existe pas");
        }

        return $this->render("intervention/interventionDetail.html.twig", [
            'intervention'=>$intervention
        ]);
    }

    #[Route('/intervention/{id}/delete', name: 'intervention_delete', methods: ['POST'])]
    public function delete(
        int $id, 
        InterventionRepository $interventionRepository, 
        EntityManagerInterface $entityManager
        ): Response
    {
        $intervention = $interventionRepository->find(id: $id);

        if (!$intervention) {
            throw $this->createNotFoundException("L'intervention avec l'id $id n'existe pas.");
        }

        $entityManager->remove($intervention);
        $entityManager->flush();
        return $this->redirectToRoute('app_companies');

    }

    #[Route('/intervention/{id}/update', name: 'intervention_update', methods: ['POST'])]
    public function update(
        int $id, 
        Request $request,
        InterventionRepository $interventionRepository, 
        EntityManagerInterface $entityManager
        ): Response
    {
        $intervention = $interventionRepository->find($id);

        if (!$intervention) {
            throw $this->createNotFoundException("L'intervention avec l'id $id n'existe pas.");
        }


        $intervention->setInterventionType("15");
        $intervention->setInterventionDateDebut(    );
        $intervention->setInterventionDateFin(      );
        $intervention->setInterventionCommentaire( );
        $entityManager->flush();
        return $this->redirectToRoute('liste_intervention');

    }




}

templates/intervention/add.html.twig
{% extends 'base.html.twig' %}
{% block body %}



{% endblock %}

templates/intervention/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}L'intervention{% endblock %}


{% block body %}

{% endblock %}

templates/intervention/interventionDetail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Intervention numéro {{intervention.id}}{% endblock %}

{% block body %}
<style>
    
</style>

<div class="container mt-5">
    <h1>Détail de l'intervention {{intervention.id}} pour  l'avion {{intervention.avion.immatriculation}}</h1>
    <div class="card">
        <div class="card primary">
            <div class="row">
                <div class="col-md-4">
                    <h4>Type d'intervention</h4>
                    <p>{{ intervention.interventionType}}
                </div>
                <div class="col-md-8">
                    <h4>Création de l'intervention</h4>
                    <p>{{ intervention.interventionDateCreation|date('d/m/Y H:m:s')}}</p>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="row mb-3">
                <div class=" col-md-4">
                    <h4>Début de l'intervention</h4>
                    <p>{{ intervention.interventionDateDebut|date('d/m/Y H:m:s') }}
                </div>
                <div class=" col-md-4">
                    <h4>Fin de l'intervention</h4>
                    <p>{{ intervention.interventionDateFin|date('d/m/Y H:m:s') }}
                </div>
                <div class=" col-md-4">
                    <h4>Type d'intervention</h4>
                    <p>{{ intervention.interventionCommentaire }}
                </div>
            </div>
        </div>
        <div class="button">
            <form method="post" action="{{ path('intervention_delete', {'id': intervention.id}) }}">
                <button type="submit" style="color: red;">Supprimer</button>
            </form>
        </div>
    </div>


    {# Partie pour la modification de l'intervention #}
    <div class="">
        <h2>Modifier l'intervention</h2>
        <form method="post" action="{{ path('intervention_update', {'id': intervention.id}) }}">

            <label for="type{{ intervention.id }}" class="form-label">Type d'intervention</label>

            <label for="dateDebut{{ intervention.id }}" class="form-label">Date de début</label>
            <input type="datetime-local" class="form-control" id="dateFin{{ intervention.id }}" name="DateDebut" 
            value="{{ intervention.interventionDateDebut|date('Y-m-d\\TH:i') }}">        
            
            <label for="dateDebut{{ intervention.id }}" class="form-label">Date de fin</label>
            <input type="datetime-local" class="form-control" id="dateFin{{ intervention.id }}" name="DateFin" 
            value="{{ intervention.interventionDateFin|date('Y-m-d\\TH:i') }}">     
            
            <textarea name="interventionCommentaire">{{ intervention.interventionCommentaire }}</textarea>
            <button type="submit">Enregistrer les modifications</button>
            
        </form>
    
    </div>

</div>
{% endblock %}

templates/intervention/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des interventions
{% endblock %}

{% block body %}
	<h1>
		Liste des interventions</h1>
	<div class="container intervention-liste">
		<table class="table table-hover">

			<thead>
				<tr>

					<th>Matricule de l'avion</th>
					<th>Type d'intervention</th>
					<th>Début de l'intervention</th>
					<th>Fin de l'intervention</th>
					<th>Commentaire</th>
					<th></th>
				</tr>
			</thead>

			{% if interventions is not empty %}
				{% for intervention in interventions %}
					<tbody>
						<tr>
							<td>
								<a href="{{ path('app_avion', {id: intervention.getAvion.immatriculation}) }}">{{ intervention.getAvion.immatriculation }}</a>
							</td>
							<td>{{ intervention.interventionType }}</td>
							<td>{{ intervention.interventionDateDebut|date('d/m/Y') }}</td>
							<td>{{ intervention.interventionDateFin|date('d/m/Y') }}</td>
							<td>{{ intervention.interventionCommentaire }}</td>
							<td>
								<a href="{{ path('intervention', {id: intervention.id}) }}">Voir détail</a>
							</td>
						</tr>
						<tr></tr>
					</tbody>
				{% endfor %}
			{% else %}
				<p>Aucune intervention trouvé.</p>
			{% endif %}
		</table>

	</div>
{% endblock %}